services:
  db:
    image: postgres:15-alpine
    container_name: mgbd-postgres
    environment:
      POSTGRES_USER: user_mgbd
      POSTGRES_PASSWORD: Dharyn123
      POSTGRES_DB: mgbd_liquibase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_mgbd -d mgbd_liquibase"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.25.0
    volumes:
      - ./db/changelog:/liquibase/changelog
    depends_on:
      db:
        condition: service_healthy
    command: >
      --url=jdbc:postgresql://db:5432/mgbd_liquibase
      --username=user_mgbd
      --password=Dharyn123
      --changeLogFile=db.changelog-master.yaml
      --searchPath=/liquibase/changelog
      update